### ISSUE TITLE
SetState() fails to create state resources without giving any error

### ISSUE THREAD

**Issue by torie** [windmill-labs/windmill-go-client#1]
### Describe the bug
When calling `SetState()` for the first time from Golang, the state is not saved, and no error is returned. If a state is already set, it can be modified and read out as expected.

```golang
package inner

import (
	wmill "github.com/windmill-labs/windmill-go-client"
)

func main() (interface{}, error) {
  if err := wmill.SetState(42); err != nil {
    return nil, err
  }

  state, err := wmill.GetState()
  if err != nil {
    return nil, err
  }
  
  return state, nil
}
```

The above code returns the following error message: 

```json
{
    "error": {
        "name": "ExecutionErr",
        "message": "ExitCode: 1, last log lines:\nNot found: Resource u/tor/affordable_flow/a/user not found"
    }
}
```

In addition, the expected state is not available in the Resources/States list.

### To reproduce
1. Create a flow with an action step using Golang
2. Call `SetState()` followed by `GetState()`

### Expected behavior
The state would be set when calling `SetState()`, after which it would appear in the Resources/States list, as well as being returned when calling `GetState()`.

### Application version
Windmill CE v1.213.0

### Additional context
Tested the behaviour in Python with the `wmill` package and this works as expected.

**Comment by rubenfiszel** [comment]
Thanks for the feedback, it's fixed on very latest which we will deploy in the next 30mins
